set nocompatible              " be iMproved, required
filetype off                  " required
" Vundle ________________________________________
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Examples --------------------------------------------------------------

" Keep Plugin commands between vundle#begin/end.

" plugin on GitHub repo
" Plugin 'tpope/vim-fugitive'

" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'

" Git plugin not hosted on GitHub
" Plugin 'git://git.wincent.com/command-t.git'

" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'

" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" -----------------------------------------------------------------------

" Installed -------------------------------------------------------------

Plugin 'honza/vim-snippets'
Plugin 'SirVer/ultisnips'
Plugin 'mtscout6/syntastic-local-eslint.vim'
"Plugin 'flazz/vim-colorschemes.git'
Plugin 'scrooloose/nerdtree.git'
Plugin 'ctrlpvim/ctrlp.vim.git'
Plugin 'tpope/vim-fugitive.git'
Plugin 'editorconfig/editorconfig-vim.git'
Plugin 'scrooloose/nerdcommenter.git'
Plugin 'vim-syntastic/syntastic.git'
Plugin 'itchyny/lightline.vim.git'
Plugin 'davidhalter/jedi-vim.git'
Plugin 'ervandew/supertab'
Plugin 'jdkanani/vim-material-theme'
"Plugin 'JamshedVesuna/vim-markdown-preview'
Plugin 'mileszs/ack.vim'
Plugin 'nathanaelkane/vim-indent-guides'


" -----------------------------------------------------------------------

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal

" see :h vundle for more details or wiki for FAQ

" NERDTree ______________________________________
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
let NERDTreeShowHidden=1

let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']

" Vim ___________________________________________

"Shame on me
set mouse=a

" Custom Keys -----------------------------------
let mapleader="ö"
map <leader>f :NERDTreeFind<cr>
map <leader>t :NERDTreeToggle<cr>
vnoremap // y/<C-R>"<CR>
" -----------------------------------------------

" Snippets --------------------------------------
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/ultisnips']
"------------------------------------------------

if &term =~ '256color'
    " Disable Background Color Erase (BCE) so that color schemes
    " work properly when Vim is used inside tmux and GNU screen.
    set t_ut=
endif

filetype plugin on
syntax on
set number
set nowrap

set tabstop=4
set softtabstop=4
set shiftwidth=4

syntax enable
set background=dark
set termguicolors " if you want to run vim in a terminal
colorscheme material-theme

noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

autocmd FileType py highlight OverLength ctermbg=red ctermfg=white guibg=#592929
autocmd FileType py match OverLength /\%81v.\+/

let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']

set clipboard=unnamedplus

" Lightline ______________________________________
let g:lightline = {
      \ 'colorscheme': 'breezy',
      \ }

" Syntastic _____________________________________
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_python_checkers = ['flake8']

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Jedi
let g:jedi#use_tabs_not_buffers = 1

" vim-markdown-preview
let vim_markdown_preview_github=1
let vim_markdown_preview_toggle=0
let vim_markdown_preview_hotkey='<C-m>'
let vim_markdown_preview_temp_file=0

" ack vim
" Use the silver searcher if available
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" :Ack normally jumps to the first file found, while :Ack! does not.
" Therefore, swap them around
cnoreabbrev Ack Ack!
nnoremap <Leader>a :Ack!<Space>

cnoreabbrev AckFromSearch AckFromSearch!
xnoremap <Leader>a "sy:Ack! <C-r>=fnameescape(@s)<CR><CR>

" vim-indent-guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#2A363E
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#37474F
